#version: '3.8'
#
#services:
#  backend:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - DATABASE_URL=postgres://postgres:root@postgres:5432/branch-service
#    depends_on:
#      - postgres
#
#  postgres:
#    image: postgres:latest
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_DB=branch-service
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=root