server:
  port: 8765

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled:  true
          # lower-case-service-id:  true
      # routes: # This section is now handled in the Java config
      #   - id:  user-service-route
      #     uri: lb://user-service
      #     predicates:
      #        - Path=/user-service/api/v1/auth/**
      #     filters:
      #        - StripPrefix=2

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
        web: DEBUG
    reactor:
      netty: DEBUG